### ISSUE TITLE
hello kitazaki

### ISSUE THREAD

**Issue by yopoo00** [kitazaki/M5Core2_atemswitcher#2]
I have a problem.
I lack knowledge, and I have been studying for 3 days without sleep.
Please help me with your great knowledge.

M5Core2_ATEM_02:53:1: error: 'TouchButton' does not name a type
 TouchButton c1 = TouchButton(0, CAMERA_BUTTON_Y, 40, 72, "c1");
 ^
M5Core2_ATEM_02:54:1: error: 'TouchButton' does not name a type
 TouchButton c2 = TouchButton(40, CAMERA_BUTTON_Y, 40, 72, "c2");
 ^
M5Core2_ATEM_02:55:1: error: 'TouchButton' does not name a type
 TouchButton c3 = TouchButton(40+40, CAMERA_BUTTON_Y, 40, 72, "c3");
 ^
M5Core2_ATEM_02:56:1: error: 'TouchButton' does not name a type
 TouchButton c4 = TouchButton(40+40+40, CAMERA_BUTTON_Y, 40, 72, "c4");
 ^
M5Core2_ATEM_02:57:1: error: 'TouchButton' does not name a type
 TouchButton c5 = TouchButton(40+40+40+40, CAMERA_BUTTON_Y, 40, 72, "c1");
 ^
M5Core2_ATEM_02:58:1: error: 'TouchButton' does not name a type
 TouchButton c6 = TouchButton(40+40+40+40+40, CAMERA_BUTTON_Y, 40, 72, "c6");
 ^
M5Core2_ATEM_02:59:1: error: 'TouchButton' does not name a type
 TouchButton c7 = TouchButton(40+40+40+40+40+40, CAMERA_BUTTON_Y, 40, 72, "c7");
 ^
M5Core2_ATEM_02:60:1: error: 'TouchButton' does not name a type
 TouchButton c8 = TouchButton(40+40+40+40+40+40+40, CAMERA_BUTTON_Y, 40, 72, "c8");
 ^
M5Core2_ATEM_02:62:1: error: 'TouchButton' does not name a type
 TouchButton b1 = TouchButton(0, MACRO_BUTTON_Y, 40, 72, "b1");
 ^
M5Core2_ATEM_02:63:1: error: 'TouchButton' does not name a type
 TouchButton b2 = TouchButton(40, MACRO_BUTTON_Y, 40, 72, "b2");
 ^
M5Core2_ATEM_02:64:1: error: 'TouchButton' does not name a type
 TouchButton b3 = TouchButton(40+40, MACRO_BUTTON_Y, 40, 72, "b3");
 ^
M5Core2_ATEM_02:65:1: error: 'TouchButton' does not name a type
 TouchButton b4 = TouchButton(40+40+40, MACRO_BUTTON_Y, 40, 72, "b4");
 ^
M5Core2_ATEM_02:66:1: error: 'TouchButton' does not name a type
 TouchButton b5 = TouchButton(40+40+40+40, MACRO_BUTTON_Y, 40, 72, "b5");
 ^
M5Core2_ATEM_02:67:1: error: 'TouchButton' does not name a type
 TouchButton b6 = TouchButton(40+40+40+40+40, MACRO_BUTTON_Y, 40, 72, "b6");
 ^
M5Core2_ATEM_02:68:1: error: 'TouchButton' does not name a type
 TouchButton b7 = TouchButton(40+40+40+40+40+40, MACRO_BUTTON_Y, 40, 72, "b7");
 ^
M5Core2_ATEM_02:69:1: error: 'TouchButton' does not name a type
 TouchButton b8 = TouchButton(40+40+40+40+40+40+40, MACRO_BUTTON_Y, 40, 72, "b8");
 ^
M5Core2_ATEM_02:77:23: error: variable or field 'buttonWasPressed' declared void
 void buttonWasPressed(TouchEvent& e) {
                       ^
M5Core2_ATEM_02:77:23: error: 'TouchEvent' was not declared in this scope
M5Core2_ATEM_02:77:35: error: 'e' was not declared in this scope
 void buttonWasPressed(TouchEvent& e) {
                                   ^
M5Core2_ATEM_02:77:23: error: variable or field 'buttonWasPressed' declared void
 void buttonWasPressed(TouchEvent& e) {
                       ^
M5Core2_ATEM_02:77:23: error: 'TouchEvent' was not declared in this scope
M5Core2_ATEM_02:77:35: error: 'e' was not declared in this scope
 void buttonWasPressed(TouchEvent& e) {
                                   ^

exit status 1
'TouchButton' does not name a type

No matter what I do, this error doesn't go away. Please help.

**Comment by kitazaki** [comment]
I experienced same error on M5Core2 library ver.0.0.6.
The M5Core2 library has been changed after atemswitcher released on ver.0.0.2.
Please try fixed code. 
https://github.com/kitazaki/M5Core2_atemswitcher/blob/main/M5Core2_ATEM_03.ino

**Comment by yopoo00** [comment]
oh my god... thanks.. im done!.. thank you!!! dear!!! 
 
 
-----Original Message-----
